name: Build Caddy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Caddy binary
        uses: actions/upload-artifact@v3
        with:
          name: caddy-binary
          path: ./caddy